version: '3'
services:
    myblast:
        build:
            context: ../../
            dockerfile: recipes/blastmysql/Dockerfile
        ports:
            - 8089:8081
        volumes:
            - /db/test:/blastdb
            - ./config.json:/config/mysql.json
    mysql:
        image: "mariadb:10.1"
        environment:
            MYSQL_ROOT_PASSWORD: "root123"
            MYSQL_DATABASE: "blast" 
            MYSQL_USER: "blast"
            MYSQL_PASSWORD: "blast123"
        volumes:
            - /tmp/data/db:/var/lib/mysql
