BootStrap: debootstrap
OSVersion: stretch
MirrorURL:  http://ftp.fr.debian.org/debian/
Include: curl php-cli php-mysql

%environment
	BLAST_PROGRAM=blastp
	BLASTDB=/blastdb
	export BLAST_PROGRAM BLASTDB

%post
	
	BLAST_VERSION=2.7.1

	cd /usr/local; curl --fail --silent --show-error --location --remote-name ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${BLAST_VERSION}/ncbi-blast-${BLAST_VERSION}+-x64-linux.tar.gz
	cd /usr/local; tar zxf ncbi-blast-${BLAST_VERSION}+-x64-linux.tar.gz; rm ncbi-blast-${BLAST_VERSION}+-x64-linux.tar.gz
	cd /usr/local/bin; ln -s /usr/local/ncbi-blast-${BLAST_VERSION}+/bin/* .

	mkdir -p /www
	mv /tmp/index.php /www/
	chmod a+rx /www/index.php

%files
	../../scripts/index.mysql.php /tmp/index.php


%labels
	Maintainer Biocorecrg
	Version 0.1.0

%runscript
	echo "Blast application!"
	cd /www
	exec php -S 0.0.0.0:8081

%startscript
	cd /www; php -S 0.0.0.0:8081
	

